//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 01:08:28 PM CEST 
//


package dpfmanager.conformancechecker.tiff.reporting.METS.niso;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for backLightType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="backLightType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Front light"/>
 *     &lt;enumeration value="Backlight 1"/>
 *     &lt;enumeration value="Backlight 2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "backLightType")
@XmlEnum
public enum BackLightType {

    @XmlEnumValue("Front light")
    FRONT_LIGHT("Front light"),
    @XmlEnumValue("Backlight 1")
    BACKLIGHT_1("Backlight 1"),
    @XmlEnumValue("Backlight 2")
    BACKLIGHT_2("Backlight 2");
    private final String value;

    BackLightType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BackLightType fromValue(String v) {
        for (BackLightType c: BackLightType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
