//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 01:08:28 PM CEST 
//


package dpfmanager.conformancechecker.tiff.reporting.METS.niso;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for componentPhotometricInterpretationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="componentPhotometricInterpretationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="Y"/>
 *     &lt;enumeration value="Cb"/>
 *     &lt;enumeration value="Cr"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "componentPhotometricInterpretationType")
@XmlEnum
public enum ComponentPhotometricInterpretationType {

    R("R"),
    G("G"),
    B("B"),
    Y("Y"),
    @XmlEnumValue("Cb")
    CB("Cb"),
    @XmlEnumValue("Cr")
    CR("Cr");
    private final String value;

    ComponentPhotometricInterpretationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ComponentPhotometricInterpretationType fromValue(String v) {
        for (ComponentPhotometricInterpretationType c: ComponentPhotometricInterpretationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
