//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 01:08:28 PM CEST 
//


package dpfmanager.conformancechecker.tiff.reporting.METS.niso;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for exposureProgramType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="exposureProgramType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Not defined"/>
 *     &lt;enumeration value="Manual"/>
 *     &lt;enumeration value="Normal program"/>
 *     &lt;enumeration value="Aperture priority"/>
 *     &lt;enumeration value="Shutter priority"/>
 *     &lt;enumeration value="Creative program (biased toward depth of field)"/>
 *     &lt;enumeration value="Action program (biased toward fast shutter speed)"/>
 *     &lt;enumeration value="Portrait mode (for closeup photos with the background out of focus)"/>
 *     &lt;enumeration value="Landscape mode (for landscape photos with the background in focus)"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "exposureProgramType")
@XmlEnum
public enum ExposureProgramType {

    @XmlEnumValue("Not defined")
    NOT_DEFINED("0"),
    @XmlEnumValue("Manual")
    MANUAL("1"),
    @XmlEnumValue("Normal program")
    NORMAL_PROGRAM("2"),
    @XmlEnumValue("Aperture priority")
    APERTURE_PRIORITY("3"),
    @XmlEnumValue("Shutter priority")
    SHUTTER_PRIORITY("4"),
    @XmlEnumValue("Creative program (biased toward depth of field)")
    CREATIVE_PROGRAM_BIASED_TOWARD_DEPTH_OF_FIELD("5"),
    @XmlEnumValue("Action program (biased toward fast shutter speed)")
    ACTION_PROGRAM_BIASED_TOWARD_FAST_SHUTTER_SPEED("6"),
    @XmlEnumValue("Portrait mode (for closeup photos with the background out of focus)")
    PORTRAIT_MODE_FOR_CLOSEUP_PHOTOS_WITH_THE_BACKGROUND_OUT_OF_FOCUS("7"),
    @XmlEnumValue("Landscape mode (for landscape photos with the background in focus)")
    LANDSCAPE_MODE_FOR_LANDSCAPE_PHOTOS_WITH_THE_BACKGROUND_IN_FOCUS("8");
    private final String value;

    ExposureProgramType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExposureProgramType fromValue(String v) {
        for (ExposureProgramType c: ExposureProgramType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
