//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 01:08:28 PM CEST 
//


package dpfmanager.conformancechecker.tiff.reporting.METS.niso;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gpsAltitudeRefType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="gpsAltitudeRefType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Sea level"/>
 *     &lt;enumeration value="Sea level reference (negative value)"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "gpsAltitudeRefType")
@XmlEnum
public enum GpsAltitudeRefType {

    @XmlEnumValue("Sea level")
    SEA_LEVEL("Sea level"),
    @XmlEnumValue("Sea level reference (negative value)")
    SEA_LEVEL_REFERENCE_NEGATIVE_VALUE("Sea level reference (negative value)");
    private final String value;

    GpsAltitudeRefType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GpsAltitudeRefType fromValue(String v) {
        for (GpsAltitudeRefType c: GpsAltitudeRefType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
    public static boolean verifyTag(String v) {
        for (GpsAltitudeRefType c: GpsAltitudeRefType.values()) {
            if (c.value.equals(v)) {
                return true;
            }
        }
        return false;
    }

}
