//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 01:08:28 PM CEST 
//


package dpfmanager.conformancechecker.tiff.reporting.METS.niso;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for grayResponseUnitType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="grayResponseUnitType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Number represents tenths of a unit"/>
 *     &lt;enumeration value="Number represents hundredths of a unit"/>
 *     &lt;enumeration value="Number represents thousandths of a unit"/>
 *     &lt;enumeration value="Number represents ten-thousandths of a unit"/>
 *     &lt;enumeration value="Number represents hundred-thousandths of a unit"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "grayResponseUnitType")
@XmlEnum
public enum GrayResponseUnitType {

    @XmlEnumValue("Number represents tenths of a unit")
    NUMBER_REPRESENTS_TENTHS_OF_A_UNIT("1"),
    @XmlEnumValue("Number represents hundredths of a unit")
    NUMBER_REPRESENTS_HUNDREDTHS_OF_A_UNIT("2"),
    @XmlEnumValue("Number represents thousandths of a unit")
    NUMBER_REPRESENTS_THOUSANDTHS_OF_A_UNIT("3"),
    @XmlEnumValue("Number represents ten-thousandths of a unit")
    NUMBER_REPRESENTS_TEN_THOUSANDTHS_OF_A_UNIT("4"),
    @XmlEnumValue("Number represents hundred-thousandths of a unit")
    NUMBER_REPRESENTS_HUNDRED_THOUSANDTHS_OF_A_UNIT("5");
    private final String value;

    GrayResponseUnitType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GrayResponseUnitType fromValue(String v) {
        for (GrayResponseUnitType c: GrayResponseUnitType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
    public static boolean verifyTag(String v) {
        for (GrayResponseUnitType c: GrayResponseUnitType.values()) {
            if (c.value.equals(v)) {
                return true;
            }
        }
        return false;
    }

}
