//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 01:08:28 PM CEST 
//


package dpfmanager.conformancechecker.tiff.reporting.METS.niso;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lightSourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="lightSourceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Daylight"/>
 *     &lt;enumeration value="Fluorescent"/>
 *     &lt;enumeration value="Tungsten (incandescent light)"/>
 *     &lt;enumeration value="Flash"/>
 *     &lt;enumeration value="Fine weather"/>
 *     &lt;enumeration value="Cloudy weather"/>
 *     &lt;enumeration value="Shade"/>
 *     &lt;enumeration value="Daylight fluorescent (D 5700 - 7100K)"/>
 *     &lt;enumeration value="Day white fluorescent (N 4600 - 5400K)"/>
 *     &lt;enumeration value="Cool white fluorescent (W 3900 - 4500K)"/>
 *     &lt;enumeration value="White fluorescent (WW 3200 - 3700K)"/>
 *     &lt;enumeration value="Standard light A"/>
 *     &lt;enumeration value="Standard light B"/>
 *     &lt;enumeration value="Standard light C"/>
 *     &lt;enumeration value="D55"/>
 *     &lt;enumeration value="D65"/>
 *     &lt;enumeration value="D75"/>
 *     &lt;enumeration value="D50"/>
 *     &lt;enumeration value="ISO studio tungsten"/>
 *     &lt;enumeration value="other light source"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "lightSourceType")
@XmlEnum
public enum LightSourceType {

    @XmlEnumValue("Daylight")
    DAYLIGHT("1"),
    @XmlEnumValue("Fluorescent")
    FLUORESCENT("2"),
    @XmlEnumValue("Tungsten (incandescent light)")
    TUNGSTEN_INCANDESCENT_LIGHT("3"),
    @XmlEnumValue("Flash")
    FLASH("4"),
    @XmlEnumValue("Fine weather")
    FINE_WEATHER("9"),
    @XmlEnumValue("Cloudy weather")
    CLOUDY_WEATHER("10"),
    @XmlEnumValue("Shade")
    SHADE("11"),
    @XmlEnumValue("Daylight fluorescent (D 5700 - 7100K)")
    DAYLIGHT_FLUORESCENT_D_5700_7100_K("12"),
    @XmlEnumValue("Day white fluorescent (N 4600 - 5400K)")
    DAY_WHITE_FLUORESCENT_N_4600_5400_K("13"),
    @XmlEnumValue("Cool white fluorescent (W 3900 - 4500K)")
    COOL_WHITE_FLUORESCENT_W_3900_4500_K("14"),
    @XmlEnumValue("White fluorescent (WW 3200 - 3700K)")
    WHITE_FLUORESCENT_WW_3200_3700_K("15"),
    @XmlEnumValue("Standard light A")
    STANDARD_LIGHT_A("17"),
    @XmlEnumValue("Standard light B")
    STANDARD_LIGHT_B("18"),
    @XmlEnumValue("Standard light C")
    STANDARD_LIGHT_C("19"),
    @XmlEnumValue("D55")
    D_55("20"),
    @XmlEnumValue("D65")
    D_65("21"),
    @XmlEnumValue("D75")
    D_75("22"),
    @XmlEnumValue("D50")
    D_50("23"),
    @XmlEnumValue("ISO studio tungsten")
    ISO_STUDIO_TUNGSTEN("24"),
    @XmlEnumValue("other light source")
    OTHER_LIGHT_SOURCE("255"),
    @XmlEnumValue("unknown")
    UNKNOWN("0");
    private final String value;

    LightSourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LightSourceType fromValue(String v) {
        for (LightSourceType c: LightSourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static boolean verifyTag(String v) {
        for (LightSourceType c: LightSourceType.values()) {
            if (c.value.equals(v)) {
                return true;
            }
        }
        return false;
    }

}
