//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 01:08:28 PM CEST 
//


package dpfmanager.conformancechecker.tiff.reporting.METS.niso;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for samplingFrequencyPlaneType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="samplingFrequencyPlaneType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="camera/scanner focal plane"/>
 *     &lt;enumeration value="object plane"/>
 *     &lt;enumeration value="source object plane"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "samplingFrequencyPlaneType")
@XmlEnum
public enum SamplingFrequencyPlaneType {

    @XmlEnumValue("camera/scanner focal plane")
    CAMERA_SCANNER_FOCAL_PLANE("camera/scanner focal plane"),
    @XmlEnumValue("object plane")
    OBJECT_PLANE("object plane"),
    @XmlEnumValue("source object plane")
    SOURCE_OBJECT_PLANE("source object plane");
    private final String value;

    SamplingFrequencyPlaneType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SamplingFrequencyPlaneType fromValue(String v) {
        for (SamplingFrequencyPlaneType c: SamplingFrequencyPlaneType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
