//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 01:08:28 PM CEST 
//


package dpfmanager.conformancechecker.tiff.reporting.METS.niso;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sensingMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="sensingMethodType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Not defined"/>
 *     &lt;enumeration value="One-chip color area sensor"/>
 *     &lt;enumeration value="Two-chip color area sensor"/>
 *     &lt;enumeration value="Three-chip color area sensor"/>
 *     &lt;enumeration value="Color sequential area sensor"/>
 *     &lt;enumeration value="Trilinear sensor"/>
 *     &lt;enumeration value="Color sequential linear sensor"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "sensingMethodType")
@XmlEnum
public enum SensingMethodType {

    @XmlEnumValue("Not defined")
    NOT_DEFINED("Not defined"),
    @XmlEnumValue("One-chip color area sensor")
    ONE_CHIP_COLOR_AREA_SENSOR("One-chip color area sensor"),
    @XmlEnumValue("Two-chip color area sensor")
    TWO_CHIP_COLOR_AREA_SENSOR("Two-chip color area sensor"),
    @XmlEnumValue("Three-chip color area sensor")
    THREE_CHIP_COLOR_AREA_SENSOR("Three-chip color area sensor"),
    @XmlEnumValue("Color sequential area sensor")
    COLOR_SEQUENTIAL_AREA_SENSOR("Color sequential area sensor"),
    @XmlEnumValue("Trilinear sensor")
    TRILINEAR_SENSOR("Trilinear sensor"),
    @XmlEnumValue("Color sequential linear sensor")
    COLOR_SEQUENTIAL_LINEAR_SENSOR("Color sequential linear sensor");
    private final String value;

    SensingMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SensingMethodType fromValue(String v) {
        for (SensingMethodType c: SensingMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
