//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 06:42:42 PM CEST 
//


package dpfmanager.conformancechecker.tiff.implementation_checker.rules.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for includeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="includeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="policychecker" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="excluderules" type="{http://www.dpfmanager.org/ProfileChecker}excludeRulesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "includeType", propOrder = {
    "policychecker",
    "excluderules"
})
public class IncludeType {

    @XmlElement(required = true)
    protected Object policychecker;
    protected ExcludeRulesType excluderules;

    /**
     * Gets the value of the policychecker property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPolicychecker() {
        return policychecker;
    }

    /**
     * Sets the value of the policychecker property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPolicychecker(Object value) {
        this.policychecker = value;
    }

    /**
     * Gets the value of the excluderules property.
     * 
     * @return
     *     possible object is
     *     {@link ExcludeRulesType }
     *     
     */
    public ExcludeRulesType getExcluderules() {
        return excluderules;
    }

    /**
     * Sets the value of the excluderules property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExcludeRulesType }
     *     
     */
    public void setExcluderules(ExcludeRulesType value) {
        this.excluderules = value;
    }

}
