//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.14 at 10:28:15 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dpfmanager.org/ProfileChecker", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dpfmanager.conformancechecker.tiff.implementation_checker.rules.model;
