//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 01:18:56 PM CEST 
//


package dpfmanager.conformancechecker.tiff.reporting.METS.premis;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dpfmanager.conformancechecker.tiff.reporting.METS.premis package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dpfmanager.conformancechecker.tiff.reporting.METS.premis
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Event.EventOutcomeInformation }
     * 
     */
    public Event.EventOutcomeInformation createEventEventOutcomeInformation() {
        return new Event.EventOutcomeInformation();
    }

    /**
     * Create an instance of {@link Event.EventIdentifier }
     * 
     */
    public Event.EventIdentifier createEventEventIdentifier() {
        return new Event.EventIdentifier();
    }

    /**
     * Create an instance of {@link Event.LinkingAgentIdentifier }
     * 
     */
    public Event.LinkingAgentIdentifier createEventLinkingAgentIdentifier() {
        return new Event.LinkingAgentIdentifier();
    }

    /**
     * Create an instance of {@link Event.LinkingObjectIdentifier }
     * 
     */
    public Event.LinkingObjectIdentifier createEventLinkingObjectIdentifier() {
        return new Event.LinkingObjectIdentifier();
    }

    /**
     * Create an instance of {@link Event.EventOutcomeInformation.EventOutcomeDetail }
     * 
     */
    public Event.EventOutcomeInformation.EventOutcomeDetail createEventEventOutcomeInformationEventOutcomeDetail() {
        return new Event.EventOutcomeInformation.EventOutcomeDetail();
    }

}
