//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 01:18:56 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.loc.gov/standards/premis/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dpfmanager.conformancechecker.tiff.reporting.METS.premis;
